### PR TITLE
Adding additional statistics to `tidy.tidycuminc()`

### PR DESCRIPTION
**Pull request by ddsjoberg**
**What changes are proposed in this pull request?**

* The `tidyi.cuminc()` method now returns the number at risk, cumulative number of obs that experienced the outcome/event, and the cumulative numbers of obs that have been censored.

@tengfei-emory this is a big update to `tidy.tidycuminc()`. Rather than doing all the calculations in `tidy.tidycuminc()`, there is an internal function `first_cuminc_tidy()` that creates the first tidy data frame, which is saved into the `cuminc()` object. The initial data frame has estimates for every observed timepoint.  The `tidy.tidycuminc()` method uses that initial data frame to obtain estimates at user-requested timepoints.

It's a very big change and now includes additional statistics. Can you do a very thorough review to ensure it is all correct? Do you feel we need additional unit tests?

--------------------------------------------------------------------------------

Checklist for PR reviewer

- [ ] PR branch has pulled the most recent updates from master branch. Ensure the pull request branch and your local version match and both have the latest updates from the master branch.
- [ ] If a new function was added, function included in `_pkgdown.yml`
- [ ] If a bug was fixed, a unit test was added for the bug check
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features. Review coverage with `covr::report()`. Before you run, set `Sys.setenv(NOT_CRAN="true")` and begin in a fresh R session without any packages loaded. 
- [ ] R CMD Check runs without errors, warnings, and notes
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation

When the branch is ready to be merged into master:
- [ ] Update `NEWS.md` with the changes from this pull request under the heading "`# tidycmprsk (development version)`". If there is an issue associated with the pull request, reference it in parentheses at the end of the update.
- [ ] Increment the version number using `usethis::use_version(which = "dev")` 
- [ ] Run `usethis::use_spell_check()` again
- [ ] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge".

### CODE REVIEW

**Comment by tengfei-emory** [comment]
I would like to have the following clarified:

What is the definition of number of at-risk? Is this number the size of the (strata-specific) risk set we used to calculate Kaplan-Meier? If that's the case, I think all subjects event-free **instantaneously before an event** should be counted. The current version excludes those who encountered the event from the risk set at the same time. 

The following code should include those who were event-free prior to t but encountered the event at t, in the risk set at time t:
`n.risk = dplyr::n() - cumsum(.data$status != 0) + (.data$status != 0)`

**Comment by tengfei-emory** [comment]
Some more issues found:

1. ` n.risk = dplyr::n() - cumsum(.data$status != 0) `: the size of the risk set is defined as sample size n minus observed failures. Do we also need to subtract censored subjects?
2. When calculating `df_n_censor` the data is not sorted by time, which means `row_number()` is not correctly assigned.
3. (Critical issue) The `cuminc_matrix_to_df` function utilizes `cmprsk::timepoints()` function. The function `cmprsk::timepoints()` returns a matrix of estimates with time as column names (as character). This essentially means that we may lose some decimal points if reaching the limit of character. When `cuminc_matrix_to_df` attempts to convert those column names (character) back to numeric, the converted `time` can be numerically different from `time` saved in `df_n_risk`, `df_n_event`, `df_n_censor` and `df_time_zero`. This will have large impacts when all those tables are merged together because `time` is numerically different.
4. When merging the tables, `NA`s are filled from the previous entry after sorting the table. I think this needs to be doubled checked especially for `n.risk` and it depends on how we define the risk set. For example, will an event for a competing failure type decrease the risk set for another failure type? 

I already have some code updates in my local commits for the above list. Let's discuss before further updating the code.

**Comment by ddsjoberg** [comment]
Thanks for the thoughtful checking. I've been thinking about our implementation overall of the `tidy()` method, and I think we should make a change to match the results of the `survival::survfit()` tidier.

``` r
survival::survfit(survival::Surv(time, status) ~ 1, survival::lung) |>
  broom::tidy()
#> # A tibble: 186 x 8
#>     time n.risk n.event n.censor estimate std.error conf.high conf.low
#>    <dbl>  <dbl>   <dbl>    <dbl>    <dbl>     <dbl>     <dbl>    <dbl>
#>  1     5    228       1        0    0.996   0.00440     1        0.987
#>  2    11    227       3        0    0.982   0.00885     1.00     0.966
#>  3    12    224       1        0    0.978   0.00992     0.997    0.959
#>  4    13    223       2        0    0.969   0.0118      0.992    0.947
#>  5    15    221       1        0    0.965   0.0126      0.989    0.941
#>  6    26    220       1        0    0.961   0.0134      0.986    0.936
#>  7    30    219       1        0    0.956   0.0142      0.983    0.930
#>  8    31    218       1        0    0.952   0.0149      0.980    0.924
#>  9    53    217       2        0    0.943   0.0163      0.974    0.913
#> 10    54    215       1        0    0.939   0.0169      0.970    0.908
#> # ... with 176 more rows
```

<sup>Created on 2021-12-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

To avoid confusing for users of the survival package (which is everyone) and our package, the stats should have the same column names AND the same interpretation. For us this means updating `n.risk`, `n.event`, `n.censor` columns to be the number at the time point rather than the (more useful) cumulative events/censored. What do you think? @tengfei-emory 

If you agree, I would suggest that you push your updates as they are now. We can chat this week about splitting the tasks ahead.

To do:
1. Update the definitions of `n.event` and `n.censor`.
2. Merge @tengfei-emory update to the `n.risk`
3. Should a cumulative version of these columns be added to the tidy tibble?
4. Add unit tests that check our tidier results against `tidy.survfit()`. The `n.risk` and `n.censor` columns be the same. The `n.event` column can be made to match with multiple calls to `survival::survfit()` (one for each competing event).

> 3. (Critical issue) The `cuminc_matrix_to_df` function utilizes `cmprsk::timepoints()` function. The function `cmprsk::timepoints()` returns a matrix of estimates with time as column names (as character). This essentially means that we may lose some decimal points if reaching the limit of character. When `cuminc_matrix_to_df` attempts to convert those column names (character) back to numeric, the converted `time` can be numerically different from `time` saved in `df_n_risk`, `df_n_event`, `df_n_censor` and `df_time_zero`. This will have large impacts when all those tables are merged together because `time` is numerically different.

Can you submit your update as a separate PR?

**Comment by tengfei-emory** [comment]
I put all my updates in a separate branch and a corresponding PR. 

Yeah we need clear definitions of n.risk, n.event and n.censor before further edit. Merging things together with more than one failure type is very tricky and we need to think more about it. 

How to handle ties in failure times may be another challenge. I don't think the current version can manage ties.

**Comment by ddsjoberg** [comment]
@tengfei-emory are all these updates in your new PR branch? can we close this one?

**Pull request merged**
