### PR TITLE
Adding "interval.event" and "interval.censor" counts.

### LINKED ISSUE #48: Don't make a release until broom's release
Make our release after this PR has been merged, and the update released to CRAN
https://github.com/tidymodels/broom/pull/1069

### PR DESCRIPTION
**Pull request by tengfei-emory**
**What changes are proposed in this pull request?**

Add number of events and censored observations for the time intervals specified by user. 

**If there is an GitHub issue associated with this pull request, please provide link.**

closes https://github.com/MSKCC-Epi-Bio/tidycmprsk/issues/49
closes #48

--------------------------------------------------------------------------------

Checklist for PR reviewer

- [ ] PR branch has pulled the most recent updates from master branch. Ensure the pull request branch and your local version match and both have the latest updates from the master branch.
- [ ] If a new function was added, function included in `_pkgdown.yml`
- [ ] If a bug was fixed, a unit test was added for the bug check
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features. Review coverage with `covr::report()`. Before you run, set `Sys.setenv(NOT_CRAN="true")` and begin in a fresh R session without any packages loaded. 
- [ ] R CMD Check runs without errors, warnings, and notes
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation

When the branch is ready to be merged into master:
- [ ] Update `NEWS.md` with the changes from this pull request under the heading "`# tidycmprsk (development version)`". If there is an issue associated with the pull request, reference it in parentheses at the end of the update.
- [ ] Increment the version number using `usethis::use_version(which = "dev")` 
- [ ] Run `usethis::use_spell_check()` again
- [ ] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge".

### CODE REVIEW

**Comment by ddsjoberg** [comment]
very nice @tengfei-emory ! can you add a unit test or two?

**Comment by ddsjoberg** [comment]
@tengfei-emory do be consistent with the survival package, let's keep the names `n.event` and `n.censor`. When the users don't include a time argument, it'll be equivalent to what we have now. And when they include a time argument, they will be the sum over the interval.

**Comment by tengfei-emory** [comment]
Got it. Should be an easy modification.

**Comment by tengfei-emory** [comment]
Still need some unit tests.

**Comment by tengfei-emory** [comment]
Added a unit test

**Review by ddsjoberg — CHANGES_REQUESTED** [review]
This is looking great @tengfei-emory !

I bumped the version requirement for broom, and removed it from `Remotes:`. Still no word on the hardhat status.

Regading the interval update: I think there is a difference in `n.event` and `n.censor` when `time = 0` is and is not specified, and they should be equal..

``` r
library(tidycmprsk)

tt <- cuminc(Surv(ttdeath, death_cr) ~ 1, trial)

tidy(tt, times = c(0, 24)) %>% 
  dplyr::select(time, outcome, estimate, n.event, n.censor)
#> # A tibble: 4 x 5
#>    time outcome            estimate n.event n.censor
#>   <dbl> <chr>                 <dbl>   <dbl>    <dbl>
#> 1     0 death from cancer     0           0        0
#> 2    24 death from cancer     0.285      57       88
#> 3     0 death other causes    0           0        0
#> 4    24 death other causes    0.275      55       88

tidy(tt, times = c(24)) %>% 
  dplyr::select(time, outcome, estimate, n.event, n.censor)
#> # A tibble: 2 x 5
#>    time outcome            estimate n.event n.censor
#>   <dbl> <chr>                 <dbl>   <dbl>    <dbl>
#> 1    24 death from cancer     0.285       0        0
#> 2    24 death other causes    0.275       0        0
```

<sup>Created on 2022-01-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by tengfei-emory** [comment]
Looks like most tests are passed. There is a warning though. I did not get this warning at my local check.

══ Warnings ════════════════════════════════════════════════════════════════════
── Warning (test-crr.R:34:3): crr() works ──────────────────────────────────────
additional arguments ignored in stop()
Backtrace:
  1. testthat::expect_error(...) test-crr.R:34:2
  7. tidycmprsk:::as_numeric_failcode(...)
  8. base::tryCatch(...) /Users/runner/work/tidycmprsk/tidycmprsk/check/tidycmprsk.Rcheck/00_pkg_src/tidycmprsk/R/crr.R:50:2
  9. base:::tryCatchList(expr, classes, parentenv, handlers)
 10. base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
 11. value[[3L]](cond)
 12. base::stop(e, call. = FALSE) /Users/runner/work/tidycmprsk/tidycmprsk/check/tidycmprsk.Rcheck/00_pkg_src/tidycmprsk/R/crr.R:58:8

[ FAIL 0 | WARN 1 | SKIP 0 | PASS 78 ]

**Comment by ddsjoberg** [comment]
I see that warning in my check too when I use `devtools::test()`, but not run in the console. It's a strange one, because we're checking that a malformed formula results in an error (which it does), but it gives a warning along the way. I think it's ok to continue with the warning.

Should i complete the review now? @tengfei-emory

**Comment by tengfei-emory** [comment]
@ddsjoberg Please feel free to merge! Thanks!

**Review by ddsjoberg — APPROVED** [review]

**Pull request merged**
