### PR TITLE
gtsummary v2.0 preparation

### LINKED ISSUE #108: Add a `gtsummary::tbl_regression.tidycrr()` method
This method is currently exported by gtsummary. But we can just maintain it from here.

### PR DESCRIPTION
**Pull request by ddsjoberg**
**What changes are proposed in this pull request?**
* Updating package to account for changes in {gtsummary} v2.0. To use `gtsummary::tbl_regression()` with `tidycmprsk::crr()` models, the {tidycmprsk} package must be loaded (to access the S3 methods below).
  - Added {broom.helpers}, {cardx}, and {aod} to Suggests field.
  - Added `tbl_regression.tidycrr()` method.
  - Added `global_pvalue_fun.tidycrr()` method, which changes the default calculation in `gtsummary::add_global_p(anova_fun)` to use the Wald test.

**If there is an GitHub issue associated with this pull request, please provide link.**
closes #108
closes https://github.com/MSKCC-Epi-Bio/tidycmprsk/issues/93

--------------------------------------------------------------------------------

Checklist for PR reviewer

- [x] PR branch has pulled the most recent updates from master branch. Ensure the pull request branch and your local version match and both have the latest updates from the master branch.
- [x] If a new function was added, function included in `_pkgdown.yml`
- [x] If a bug was fixed, a unit test was added for the bug check
- [x] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [x] Code coverage is suitable for any new functions/features. Review coverage with `covr::report()`. Before you run, set `Sys.setenv(NOT_CRAN="true")` and begin in a fresh R session without any packages loaded. 
- [x] R CMD Check runs without errors, warnings, and notes
- [x] `usethis::use_spell_check()` runs with no spelling errors in documentation
- [x] Test the update does not break any reverse dependencies with `revdepcheck::revdep_check()` (https://github.com/r-lib/revdepcheck)

When the branch is ready to be merged into master:
- [x] Update `NEWS.md` with the changes from this pull request under the heading "`# tidycmprsk (development version)`". If there is an issue associated with the pull request, reference it in parentheses at the end of the update.
- [x] Increment the version number using `usethis::use_version(which = "dev")` 
- [x] Run `usethis::use_spell_check()` again
- [x] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge".

### CODE REVIEW

**Comment by ddsjoberg** [comment]
@tengfei-emory we have to make a release to stay on CRAN. Can you review this PR?

**Comment by tengfei-emory** [comment]
@ddsjoberg Do you have an ideal timeline? It would work better for me if I can review after JSM.

**Comment by ddsjoberg** [comment]
> @ddsjoberg Do you have an ideal timeline? It would work better for me if I can review after JSM.

Thanks @tengfei-emory ! 

There failures are showing on CRAN already, but I haven't received an email indicating we need to update yet. Once that email arrives, we have 2 weeks to resubmit.
https://cran.r-project.org/web/checks/check_results_tidycmprsk.html

**Comment by ddsjoberg** [comment]
Hi @tengfei-emory , 

I got the email from CRAN last night, and we need to make the new release to CRAN now. How does this fit in your timeline?

**Comment by tengfei-emory** [comment]
I am on vacation this week. Is it possible to finish the review before the end of next week?

**Comment by ddsjoberg** [comment]
> I am on vacation this week. Is it possible to finish the review before the end of next week?

That should work! Thanks @tengfei-emory !!

**Comment by tengfei-emory** [comment]
I received the following error messages when running `build_site()`:

Any ideas about the cause of this?

```
> pkgdown::build_site()
-- Installing package into temporary library -----------------------------------------------------
Warning: package ‘tidycmprsk’ is in use and will not be installed
== Building pkgdown site =======================================================
Reading from: 'C:/Users/feit1/OneDrive - Memorial Sloan Kettering Cancer Center/Documents/GitHub/tidycmprsk'
Writing to:   'C:/Users/feit1/OneDrive - Memorial Sloan Kettering Cancer Center/Documents/GitHub/tidycmprsk/docs/dev'
-- Initialising site -----------------------------------------------------------
-- Building home ---------------------------------------------------------------
Reading '.github/CODE_OF_CONDUCT.md'
Reading '.github/CONTRIBUTING.md'
Reading '.github/PULL_REQUEST_TEMPLATE.md'
Reading '.github/SUPPORT.md'
Reading 'LICENSE.md'
Registered S3 methods overwritten by 'tidycmprsk':
  method                    from     
  global_pvalue_fun.tidycrr gtsummary
  tbl_regression.tidycrr    gtsummary
-- Building function reference -------------------------------------------------
Error: 
! in callr subprocess.
Caused by error in `check_missing_topics(rows, pkg)`:
! All topics must be included in reference index
✖ Missing topics: gtsummary_s3_methods
ℹ Either add to _pkgdown.yml or use @keywords internal
ℹ See `$stdout` and `$stderr` for standard output and error.
Type .Last.error to see the more details.
```

**Comment by tengfei-emory** [comment]
`revdepcheck::revdep_check()` doesn't really work from my end. Can we skip this from the checklist?

**Comment by tengfei-emory** [comment]
Do we want to increase the version number?

**Review by tengfei-emory — APPROVED** [review]
The current version passed check from my end.

**Comment by tengfei-emory** [comment]
Somehow there is one check not starting running (ubuntu-18.04).

Other than that, there is no error messages from my end. I already approved the pull request but am still waiting for the check to complete so that the branches can be merged.

**Comment by ddsjoberg** [comment]
thank you @tengfei-emory !!!

I'll send it to CRAN next week!

**Pull request merged**
